# fly.toml app configuration file generated for bytecourses on 2025-11-18T10:57:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bytecourses'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.25.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = 'stop'
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "run-app --storage=sql"
